name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [labeled]

jobs:
  test:
    if: github.event.pull_request.labels.*.name == 'run-tests'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run tests
        run: cargo test -- --nocapture
